theme: jekyll-theme-minimal
title: OpenRange Labs Common Lib
description: The Common Lib is a Java Library that can be assed to Spring Boot Applications to help bootstrap some of the functionality across other applications. Bookmark this to keep an eye on my project updates!