theme: jekyll-theme-minimal
title: OpenRange Labs Common Lib
description: The Common Lib is a Java Library that can be added to Spring Boot Applications to help bootstrap some of the functionality across other applications.
# Remove any custom CSS references